service: meme-maker

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  mememake:
    handler: handler.mememake
    layers:
      - arn:aws:lambda:us-east-1:175033217214:layer:graphicsmagick:2
    events:
      - http:
          method: 'get'
          path: '/mememake'

plugins:
  - serverless-offline
